# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b41b7ce34ff687e8cc212bd844a86af975d51711d27aca102682288dae7a0e913933c4d0922443d86ae63e8455cdef5c8f6eeba2c42870c13fc1d270d5736f

test:
  secret_key_base: a76a3fdf49011037142de07394471b50458c91ceac3d08b90988652f641b102d55e9b72cd2e9d906417ed7565276e5d92ab39cf5b8e75fe05e4931ff1199b3ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
